extension_dir="C:\\Users\\Hp\\AppData\\Local\\Microsoft\\WinGet\\Packages\\PHP.PHP.8.3_Microsoft.Winget.Source_8wekyb3d8bbwe\\ext"
extension=openssl
extension=mbstring
extension=fileinfo
extension=pdo_sqlite
extension=sqlite3
extension=curl
extension=intl

date.timezone=Europe/Istanbul
memory_limit=512M
extension=zip
